madrisan/nagios-plugins-linux

- plugins/check_load.c
> Fixed performance data output for check_load

- plugins/check_multipath.c
RHEL7 no longer has a multipathd socket file in the file system at /var/run/multipathd.sock instead it uses an "abstract namespace" socket (see "man unix" for details).  This patch allows support for this to be enabled at compile time by declaring the socketfile name to begin with a @ symbol (as they appear in netstat output)
For RHEL6 compile as before, but for RHEL7 you need to compile it as:
./configure --with-socketfile="@/org/kernel/linux/storage/multipathd"
make
make install
> Deal with multipath sockets that do not exist in the filesystem

- configure.ac
- include/Makefile.am
- include/container.h
- include/json.h
- include/url_encode.h
- lib/Makefile.am
- lib/container.c
- lib/json.c
- lib/url_encode.c
- libtool
- m4/libcurl.m4
- plugins/Makefile.am
- plugins/check_docker.c
First attempt to provide a module for monitoring docker.
> Merge docker branch

- NEWS
- README.md
- configure.ac
> Version 23

- README.md
- libtool
- packages/Makefile.am
> build: support Fedora 29 packaging

- plugins/check_cpufreq.c
This change addresses the GitHub issue #12 opened by sbraz.
> check_cpufreq: make it possible to output the value in Hz/kHz/mHz/gHz

- NEWS
- README.md
- configure.ac
> Version 24

- README.md
- debian/changelog
- packages/Makefile.am
- packages/multibuild.sh
- tests/Makefile.am
The command "make -C packages debian-buster" should package nagios-plugins-linux for Debian Buster.
> Make possible to create Debian Buster packages

- tests/Makefile.am
- tests/tslibperfdata.c
New unit test for the perfdata library.
> tests: new unit test for lib/perfdata.c

- README.md
As discussed, here's the PR to update the doc.
> Document Gentoo package availability in README.md

- configure.ac
- include/Makefile.am
- include/container_podman.h
- lib/Makefile.am
- lib/container_podman.c
- plugins/Makefile.am
- plugins/check_podman.c
Add a new plugin for checking podman containers through varlink.
Currently it only reports the number of running containers.
> New (alpha) plugin check_podman

- configure.ac
> build: fix check for linux/if.h on Ubuntu

- packages/multibuild.sh
- packages/specs/nagios-plugins-linux.spec.in
> build: package also check_podman on Fedora

- .github/workflows/ubuntu-build-check.yml
> Check github workflows

- .github/workflows/build-checks.yml
> build: add multiple oses to github workflow

- debian/changelog
- debian/control
- debian/nagios-plugins-linux-clock.install
- debian/nagios-plugins-linux-cpu.install
- debian/nagios-plugins-linux-cpufreq.install
- debian/nagios-plugins-linux-cswch.install
- debian/nagios-plugins-linux-docker.install
- debian/nagios-plugins-linux-fc.install
- debian/nagios-plugins-linux-ifmountfs.install
- debian/nagios-plugins-linux-intr.install
- debian/nagios-plugins-linux-iowait.install
- debian/nagios-plugins-linux-load.install
- debian/nagios-plugins-linux-memory.install
- debian/nagios-plugins-linux-multipath.install
- debian/nagios-plugins-linux-nbprocs.install
- debian/nagios-plugins-linux-network.install
- debian/nagios-plugins-linux-paging.install
- debian/nagios-plugins-linux-pressure.install
- debian/nagios-plugins-linux-readonlyfs.install
- debian/nagios-plugins-linux-swap.install
- debian/nagios-plugins-linux-tcpcount.install
- debian/nagios-plugins-linux-temperature.install
- debian/nagios-plugins-linux-uptime.install
- debian/nagios-plugins-linux-users.install
- debian/nagios-plugins-linux.dirs
- debian/rules
Build a Debian multi-package instead of a single package providing all binary plugins.
Closes #79
> packages: Build a Debian multi-package

- .github/workflows/build-checks.yml
> tests: use the latest stable OSes in GitHub workflow

- debian/Makefile.am
- debian/changelog
- debian/copyright
- debian/nagios-plugins-linux-network.links
Thanks to by [sbraz](https://github.com/sbraz) for pointing this out
in the issue:
https://github.com/madrisan/nagios-plugins-linux/issues/89
> Fix the build of Debian packages

- .github/workflows/build-checks.yml
> CI: switch to Debian 11 in GitHub Workflow

- include/cpudesc.h
- include/sysfsparser.h
- lib/container_docker_memory.c
- lib/cpudesc.c
- lib/cputopology.c
- lib/sysfsparser.c
- plugins/check_cpu.c
- plugins/check_cpufreq.c
- plugins/check_fc.c
- plugins/check_load.c
- plugins/check_temperature.c
> Make sure sysfs is mounted when needed

- contrib/icinga2/CheckCommands.conf
Sorry, missed something last time :-)
> Add missing values

- .github/workflows/build-checks.yml
- README.md
> workflows: update os versions used in tests

- .github/workflows/build-checks.yml
- README.md
- packages/Makefile.am
> Add Fedora 36 and drop Fedora 33 support

- include/Makefile.am
- include/files.h
- lib/Makefile.am
- lib/files.c
- plugins/Makefile.am
- plugins/check_filecount.c
New plugin check_filecount to get the number of files present in a list of directories.
> New plugin check_filecount

- AUTHORS
- include/files.h
- include/xstrton.h
- lib/files.c
- lib/xstrton.c
- plugins/check_filecount.c
> filecount: new cmdline option --size

- include/files.h
- lib/files.c
- plugins/check_filecount.c
Add more labels to the perfdata of the check_filecount check.
> check_filecount: more verbose perfdata

- .github/workflows/build-checks.yml
- tests/Makefile.am
- tests/tslibfiles_age.c
- tests/tslibfiles_hiddenfile.c
- tests/tslibfiles_size.c
- tests/tslibxstrton_agetoint64.c
- tests/tslibxstrton_sizetoint64.c
> Add some unit tests for lib/files

- plugins/check_memory.c
Feature asked by @mdicss.
See: https://github.com/madrisan/nagios-plugins-linux/discussions/120
> check_memory: support new units kiB/MiB/GiB

- .github/workflows/build-checks.yml
- README.md
- packages/Makefile.am
- packages/specs/nagios-plugins-linux.spec.in
> packages: add support for Fedora 37
