madrisan/nagios-plugins-linux

include/container.h
lib/container_count.c
plugins/check_docker.c
tests/testutils.c
tests/tslibcontainer_count.c
tests/tsliburlencode.c
tests/tststestutils.c

of the following types:
* argument cannot be negative;
* explicit null dereference count;
* less-than-zero comparison of an unsigned value is never true;
* logically daed code;
* resource leak.
mainly in the tests folder but also in lib/container_count.c

Fix severy issues reported by Coverity

---

plugins/check_cpufreq.c

See: https://www.kernel.org/doc/Documentation/cpu-freq/user-guide.txt
This issue has been reported by "sbraz". Thanks!

check_cpufreq: the frequences returned by sysfs are in KHz

---

configure.ac
m4/cc_try_cflags.m4

Compiling the source code with clang (7.0.0) two annoying
warning messages are printed at each compiler invocation:
warning: unknown warning option '-Wformat-signedness' [-Wunknown-warning-option]
warning: unknown warning option '-Wstringop-truncation'; did you mean '-Wstring-conversion'? [-Wunknown-warning-option]
Modify the m4 `macro cc_try_cflags' to fix this issue.

build: fix unsupported warning options for clang

---

plugins/check_clock.c
plugins/check_users.c

Fix two issues reported by the lgtm code analyser:
- Call to **localtime** is potentially dangerous (plugins/check_clock.c)
- Call to **ctime** is potentially dangerous (plugins/check_users.c)

Fix two security issues reported by lgtm analyzer

---

README.md
packages/Makefile.am

The `make -C packages command` does not support Fedora 30.
Add a make target for such a Linux distribution and make `fedora-latest` and alias for Fedora 30. 

Make rpm packages for Fedora 30

---

tests/tslibcontainer_count.c

Fix the following issue reported by the clang static analyser v8:
```
tslibcontainer_count.c:83:7: warning: 1st function call argument is an uninitialized value
free (perfdata);
^~~~~~~~~~~~~~~
```

Fix an issue reported by the clang static analyser v8

---

include/Makefile.am
include/meminfo.h
include/perfdata.h
include/string-macros.h
include/thresholds.h
lib/Makefile.am
lib/perfdata.c
lib/thresholds.c
plugins/check_memory.c

Add min, max, warning and critical in perfdata for mem_available
and mem_used as asked by sbraz (issue #32).

check_memory: add perfdata to mem_available and mem_used

---

configure.ac

Add the option '--disable-libcurl' to the script 'configure'.
This make it possible to disable at build time the linking of the
curl libraries installed in the system where the package is built.
This option only affects the plugin 'check_docker' (which is not
compiled in this case).

build: add a build option to disable libcurl

---

README.md
packages/Makefile.am
packages/multibuild.sh

Now that the Docker image for CentOS 8 is available,
the build of the packages for this OS should can be added.
Add a new makefile target for this OS: `centos-8`

packages: support build of rpm packages for CentOS 8

---

README.md
packages/Makefile.am

Make it possible to create rpm packages for Fedora 31 using docker or podman.

packages: add support for Fedora 31

---

include/progname.h

As reported by 'sbraz', the build stops with the error message:
(.bss+0x8): multiple definition of `program_name'
(.bss+0x0): multiple definition of `program_name_short'
This flag will be apparently enabled by default in gcc 10.
Fix this build problem by correctly referencing as extern both
the variables in the header file.

The build fails when '-fno-common' is added to CFLAGS

---

lib/processes.c
plugins/check_fc.c

Hi Davide,
Here is another patch for a build problem. Initially reported at https://bugs.gentoo.org/717038
Without these includes, the build fails with musl:
``` 
error: PATH_MAX undeclared (first use in this function)
```

Fix build with musl by including limits.h when PATH_MAX is used

---

lib/meminfo_procps.c
lib/vminfo_procps.c
tests/tslibmeminfo_interface.c

Fix the build when '--enable-libprocps' is passed to configure.

Fix build linked to the procps-ng newlib library

---

include/netinfo.h
lib/netinfo.c
plugins/check_network.c

When a link has a defined speed (returned by ioctl SIOCETHTOOL)
do add to the pluging output the min and max performance data in bytes.
Example:
link enp1s0: 1Gbit/s (full duplex)
--> enp1s0_txbyte/s=781;;;0;125000000
enp1s0_rxbyte/s=1083;;;0;125000000

check_network: add performance data for links with available speed

---

include/netinfo-private.h
include/netinfo.h
lib/netinfo-private.c
lib/netinfo.c

The WireGuard interfaces are of type AF_INET and were
previously skipped (only the AF_PACKET ones were reported).
Add all the AF_INET/AF_INET6 ones that have no AF_PACKET
correspondent..
This should (partially) solve the issue opened by <https://github.com/sbraz>

lib/netinfo: display WireGuard interfaces

---

.codeclimate.yml
include/netinfo-private.h
include/netinfo.h
lib/netinfo-private.c
lib/netinfo.c

Switch to linux rtnetlink to be able to get the required
informations for all the network interfaces available.
This new implementation in particular works also for the
WireGuard interfaces.

lib/netinfo*: switch from getifaddrs glib call to linux rtnetlink

---

README.md
packages/Makefile.am
packages/multibuild.sh

Make it possible to build rpm packages for Fedora 33
by using the command "make -C packages fedora-33".

packages: make it possible to build packages for Fedora 33

---

README.md
packages/Makefile.am
packages/docker-shell-helpers/docker-shell-helpers.sh
packages/multibuild.sh
packages/specs/APKBUILD.in
packages/specs/Makefile.am

Make it possible to create basic Linux Alpine .apk packages
by running the command: make -C packages alpine-3.12
As usual this make command requires docker or podman to work.

packages: add Alpine package creation

---

include/string-macros.h
include/sysfsparser.h
lib/sysfsparser.c
plugins/check_temperature.c

Add the device information for the thermal zone when available.
If not says it's a "Virtual device" (hope it's correct).
Example of the new output:
temperature OK - 39.0°C (thermal zone: 2 [EXTZ], type: "acpitz") | temp=39C;0;128
temperature OK - 39.0°C (thermal zone: 3 [LOCZ], type: "acpitz") | temp=39C;0;128
temperature OK - 31.0°C (thermal zone: 4 [BATZ], type: "acpitz") | temp=31C;0;128
temperature OK - 39.5°C (thermal zone: 6 [Virtual device], type: "pch_skylake") | temp=39C;0;115
temperature OK - 41.0°C (thermal zone: 7 [Virtual device], type: "iwlwifi_1") | temp=41C
temperature OK - 44.0°C (thermal zone: 8 [Virtual device], type: "x86_pkg_temp") | temp=44C

check_temperature: improve the output message

---

configure.ac
plugins/Makefile.am

Fix the regression introduced by commit 07c1239:
libtool: link: gcc -std=gnu99 -Wall -Wformat -Wformat -Wformat-security -Wformat-signedness -Wimplicit-fallthrough=2 -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Wshadow -Wsign-compare -Wstrict-aliasing=2 -Wstringop-truncation -Wunused -Wstack-protector -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fpie -fPIE -g -O2 -fdebug-prefix-map=/home/stb-tester/workspace/build/nagios-plugins-linux/nagios-plugins-linux-28=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,relro -o check_network check_network.o  ../lib/libutils.a
/usr/bin/ld: ../lib/libutils.a(netinfo.o): in function `netinfo':
./lib/netinfo.c:88: undefined reference to `ceil'
/usr/bin/ld: ./lib/netinfo.c:93: …

build: check_network fails to link on ARM

---

lib/netinfo-private.c

Fix the alert:
Comparison is always false because ... = ... >= 0.
detected by the LGTM static code analyzer.

lib/netinfo: fix a LGTM alert

---

README.md
packages/Makefile.am

Make it possible to build the packages for Debian 11 ("bullseye").
Drop the support for the old Debian 8 ("Jessie").

packages: add Debian 11 and drop Debian 8

---

lib/pressure.c

Display values per second regardless of the delay, and ensure the delta of "some" is calculated correctly.

Pressure fixes

---

README.md
packages/Makefile.am
packages/multibuild.sh

Support packaging for CentOS Stream version 8 and 9, now
that CentOS 8 died a premature death.

packages: add support for CentOS Stream

---

.github/workflows/build-checks.yml
configure.ac

Fix the warnings:
configure.ac:52: warning: The macro `AC_PROG_CC_STDC' is obsolete.
configure.ac:52: You should run autoupdate.
./lib/autoconf/c.m4:1666: AC_PROG_CC_STDC is expanded from...
configure.ac:52: the top level
configure.ac:229: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:229: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:229: the top level
Announcements:
- https://lists.gnu.org/archive/html/autotools-announce/2020-12/msg00001.html
- https://lists.gnu.org/archive/html/autotools-announce/2021-01/msg00000.html

configure: update to autoconf 2.71

---

lib/container_docker_memory.c

Fix the following issue:
In file included from tslibcontainer_docker_memory.c:37:
./../lib/container_docker_memory.c:102:11: warning: Although the value
stored to 'chread' is used in the enclosing expression, the value is
never actually read from 'chread' [deadcode.DeadStores]
while ((chread = getline (&line, &len, fp)) != -1)
^        ~~~~~~~~~~~~~~~~~~~~~~~~~

bug#112: fix an issue reported by clang-analyzer

---

include/files.h
lib/files.c
plugins/check_filecount.c

Only count files that match PATTERN, where PATTERN is a shell-like  " wildcard" as understood by fnmatch(3).

filecount: new cmdline option --name

---

tests/Makefile.am
tests/testutils.c
tests/tslibfiles_filecount.c

Example of the output:
1) check function files_filecount (default)                          ... OK
2) check function files_filecount (default + hidden)                 ... OK
3) check function files_filecount (default - symlinks)               ... OK
4) check function files_filecount (regular only)                     ... OK
5) check function files_filecount (regular + hidden)                 ... OK
6) check function files_filecount (regular + symlinks)               ... OK
7) check function files_filecount (recursive)                        ... OK
8) check function files_filecount (recursive + regular)              ... OK
9) check function files_filecount (recursive + hidden)               ... OK
10) check function files_filecount (recursive - symlinks)             ... OK
11) check …

Add a unit test for filecount in lib/files

---

.github/workflows/build-checks.yml
configure.ac

Exit with an error message when:
* libvarlink is not available and the option --enable-libvarlink is used
* libcurl is not available and the option --enable-libcurl is used because in this case libcurl/libvarlink support is purposely required.
Bug reported by @sbraz

configure: do not silently ignore missing libcurl and libvarlink

---

lib/netinfo-private.c

Fixes: https://github.com/madrisan/nagios-plugins-linux/issues/126
The `bind()` call can fail when `getpid()` is used as `nl_pid`, application is containerized and host network is used because process ids are not unique between host and container environments.  
When 0 is used as `nl_pid` it's up to kernel to assign netlink address.
This fix is currently tested in our environment. I will ping you if it fixes issue.

lib/netinfo-private: don't enforce nl_pid

---

.github/workflows/build-checks.yml
configure.ac
plugins/check_users.c

It seems that the glibc developers don't want to fix the year 2038 problem in the utmp.h/utmpx.h/lastlog.h interfaces but prefer to deprecate them, so prefer the analogous functionality provided by systemd when available.

check_users: fix an issue related to the Y2038 unix bug

---

lib/netinfo-private.c

CC       netinfo-private.o
netinfo-private.c:138:34: warning: field 'req' with variable sized type
'struct ethtool_link_settings' not at the end of a struct or class is a
GNU extension [-Wgnu-variable-sized-type-not-at-end]
138 |     struct ethtool_link_settings req;
|                                  ^
1 warning generated.

lib/netinfo-private: fix Clang 17 warning

---

AUTHORS
plugins/check_memory.c

warning/Influxdb2Writer: Ignoring invalid perfdata for
checkable 'px1!Memory' and command 'check_memory' with
value: vmem_pageouts/s=8926,
Comma is not allowed in perfdata.

fix(check_memory): remove comma from perfdata

---

configure.ac

Rename --with-systemd to --enable-systemd for consistency
with the other optional boolean options.

fix(configure): rename cmdline option --with-systemd

---

contrib/icinga2/CheckCommands.conf

Previously the time reference value was evaluated only during the startup of Icinga 2 and therefore a fixed point in time.
This change makes it a function which gets evaluated every time the check is executed.

Fix Icinga 2 config for check_clock
